title: "Sofia Franco Website"
author: "Sofia Franco"
logo: "/assets/img/logo.png"
description: This website helps to higlight the work that i have done as part of my mayor and as part of my class.
google_analytics:
theme: jekyll-theme-cayman
